### ISSUE TITLE
startup fails because of already used shortcut

### ISSUE THREAD

**Issue by Anyqax** [postprintum/devcomrade#27]
When I build and run devcomrade, I get the error that the shortcut for "OpenNotepad" is already registered.
I didn't find a config value to change it to something else.

**Comment by noseratio** [comment]
It's [here in `App.config`](https://github.com/postprintum/devcomrade/blob/98742a09e61b9d2ca8ba8c7cf3cd19fd4d2d6d4c/DevComrade/App.config#L29):

```
    <hotkey name="OpenNotepad" menuItem="Open Internal Notepad" mods="0x8" vkey="0xDC" />
```
It's <kbd>Win</kbd>+<kbd>|</kbd> by default, looks like this combo may be taken by some other app on your system. Try changing it to some other combination, or just comment out this line to test:

```
<!--     <hotkey name="OpenNotepad" menuItem="Open Internal Notepad" mods="0x8" vkey="0xDC" /> -->
```

**Comment by Anyqax** [comment]
ah, thx, just checked those json configs in the publish folder
works when I comment it out 👍
